const ACCOUNT_SIGNUP_LOADING = 'ACCOUNT_SIGNUP_LOADING';
const ACCOUNT_SIGNUP_SUCCESS = 'ACCOUNT_SIGNUP_SUCCESS';
const ACCOUNT_SIGNUP_ERROR = 'ACCOUNT_SIGNUP_ERROR';

const ACCOUNT_SIGNIN_LOADING = 'ACCOUNT_SIGNIN_LOADING';
const ACCOUNT_SIGNIN_SUCCESS = 'ACCOUNT_SIGNIN_SUCCESS';
const ACCOUNT_SIGNIN_ERROR = 'ACCOUNT_SIGNIN_ERROR'; 

const ACCOUNT_SET_LOGOUT = 'ACCOUNT_SET_LOGOUT';

export {
  ACCOUNT_SIGNUP_LOADING,
  ACCOUNT_SIGNUP_SUCCESS,
  ACCOUNT_SIGNUP_ERROR,

  ACCOUNT_SIGNIN_LOADING,
  ACCOUNT_SIGNIN_SUCCESS,
  ACCOUNT_SIGNIN_ERROR,

  ACCOUNT_SET_LOGOUT,
};