const ALBUMS_SET_NEW_RELEASED_LOADING = 'ALBUMS_SET_NEW_RELEASED_LOADING';
const ALBUMS_SET_NEW_RELEASED_SUCCESS = 'ALBUMS_SET_NEW_RELEASED_SUCCESS';
const ALBUMS_SET_NEW_RELEASED_ERROR = 'ALBUMS_SET_NEW_RELEASED_ERROR';

const ALBUMS_SET_FEATURED_PLAYLIST_LOADING = 'ALBUMS_SET_FEATURED_PLAYLIST_LOADING';
const ALBUMS_SET_FEATURED_PLAYLIST_SUCCESS = 'ALBUMS_SET_FEATURED_PLAYLIST_SUCCESS';
const ALBUMS_SET_FEATURED_PLAYLIST_ERROR = 'ALBUMS_SET_FEATURED_PLAYLIST_ERROR';

const ALBUMS_SET_CATEGORIES_LOADING = 'ALBUMS_SET_FEATURED_PLAYLIST_LOADING';
const ALBUMS_SET_CATEGORIES_SUCCESS = 'ALBUMS_SET_CATEGORIES_SUCCESS';
const ALBUMS_SET_CATEGORIES_ERROR = 'ALBUMS_SET_CATEGORIES_ERROR';

export {
  ALBUMS_SET_NEW_RELEASED_LOADING,
  ALBUMS_SET_NEW_RELEASED_SUCCESS,
  ALBUMS_SET_NEW_RELEASED_ERROR,

  ALBUMS_SET_FEATURED_PLAYLIST_LOADING,
  ALBUMS_SET_FEATURED_PLAYLIST_SUCCESS,
  ALBUMS_SET_FEATURED_PLAYLIST_ERROR,

  ALBUMS_SET_CATEGORIES_LOADING,
  ALBUMS_SET_CATEGORIES_SUCCESS,
  ALBUMS_SET_CATEGORIES_ERROR,
};
