const APP_SET_TITLE = 'APP_SET_TITLE';

const APP_SET_SPOTIFY_CREDENTIALS_LOADING = 'APP_SET_SPOTIFY_CREDENTIALS_LOADING'; 
const APP_SET_SPOTIFY_CREDENTIALS_SUCCESS = 'APP_SET_SPOTIFY_CREDENTIALS_SUCCESS'; 
const APP_SET_SPOTIFY_CREDENTIALS_ERROR = 'APP_SET_SPOTIFY_CREDENTIALS_ERROR'; 

export { 
  APP_SET_TITLE,
  APP_SET_SPOTIFY_CREDENTIALS_LOADING,
  APP_SET_SPOTIFY_CREDENTIALS_SUCCESS,
  APP_SET_SPOTIFY_CREDENTIALS_ERROR
};
